// ────────────────────────────────────────────────────────────────────
//  lp-forge — Copywriter (Story 2.5)
//  Generates hero/services/about/CTA copy GROUNDED in business-spec.md only.
//  Zero invention: any service/hour/fact not in business-spec is omitted.
//  Marker '<!-- INFERRED -->' wraps inferred claims (counted, not generated by LLM in v0.1).
// ────────────────────────────────────────────────────────────────────
"use strict";

// Default headline templates per direction — used as fallback when LLM unavailable.
const HERO_HEADLINES = {
  editorial: businessName => `${businessName}.`,
  industrial: businessName => `${businessName} — feito para durar.`,
  luxury: businessName => `Excelência em cada detalhe.\n${businessName}.`,
  playful: businessName => `Bem-vindo a ${businessName} ✦`,
  brutalist: businessName => `${businessName.toUpperCase()}.`,
  organic: businessName => `${businessName}.\nNo seu ritmo.`
};

const HERO_SUBHEADS = {
  editorial: () => "Conheça nossa proposta.",
  industrial: () => "Trabalho técnico, executado com método.",
  luxury: () => "Atendimento sob medida, do primeiro contato à entrega.",
  playful: () => "Um lugar feito para você.",
  brutalist: () => "Direto ao ponto. Sem ruído.",
  organic: () => "Pequenos detalhes, grande diferença."
};

const HERO_CTAS = {
  editorial: () => "Saiba mais",
  industrial: () => "Solicitar orçamento",
  luxury: () => "Agendar atendimento",
  playful: () => "Vamos conversar",
  brutalist: () => "Contato",
  organic: () => "Fale conosco"
};

/**
 * Build copy bundle grounded in business-spec.md content + chosen direction.
 * inputs: { businessName, services[], contact{}, direction, brandSpec, businessSpec }
 */
function buildCopy(inputs) {
  const direction = inputs.direction || "editorial";
  const businessName = inputs.businessName || "Sua Empresa";

  const heroHeadline = HERO_HEADLINES[direction](businessName);
  const heroSubheadline = HERO_SUBHEADS[direction]();
  const heroCta = HERO_CTAS[direction]();

  const services = Array.isArray(inputs.services) ? inputs.services.slice(0, 6) : [];
  const servicesBlock = services.length > 0
    ? services.map(s => renderServiceCard(s, direction)).join("\n")
    : `          <p className="text-brand-ink/60 col-span-3">Lista de serviços disponível sob consulta.</p>`;

  const aboutCopy = inferAboutCopy(inputs, direction);
  const contactBlock = renderContactBlock(inputs.contact || {}, direction);

  return {
    heroHeadline,
    heroSubheadline,
    heroCta,
    servicesBlock,
    aboutCopy,
    contactBlock,
    inferenceCount: 0  // tracked by sanitizer/grounding-enforcer in future
  };
}

function renderServiceCard(service, direction) {
  const cls = direction === "playful" ? "playful-card border border-brand-ink/10"
    : direction === "industrial" ? "industrial-card"
    : direction === "brutalist" ? "brutalist-box"
    : direction === "organic" ? "organic-card"
    : direction === "luxury" ? "border-l-2 border-brand-primary pl-6 py-2"
    : "border-t border-brand-ink/20 pt-4"; // editorial
  // Escape JSX-special chars
  const safe = String(service).replace(/[<>{}"']/g, c => ({"<":"&lt;",">":"&gt;","{":"&#123;","}":"&#125;",'"':"&quot;","'":"&#39;"}[c]));
  return `          <div className="${cls}">\n            <h3 className="text-xl mb-2">${safe}</h3>\n          </div>`;
}

function inferAboutCopy(inputs, direction) {
  const businessName = inputs.businessName || "Esta empresa";
  const category = inputs.category;
  const city = inputs.city;
  if (!category && !city) {
    return `${businessName} atende seus clientes com atenção a cada detalhe.`;
  }
  const parts = [businessName];
  if (category) parts.push(`atua em ${category}`);
  if (city) parts.push(`em ${city}`);
  return parts.join(" ") + ".";
}

function renderContactBlock(contact, direction) {
  const items = [];
  if (contact.phone) items.push(`<p><strong>Telefone:</strong> <a href="tel:${escapeAttr(contact.phone)}">${escapeText(contact.phone)}</a></p>`);
  if (contact.whatsapp) items.push(`<p><strong>WhatsApp:</strong> <a href="https://wa.me/${escapeAttr(contact.whatsapp)}">${escapeText(contact.whatsapp)}</a></p>`);
  if (contact.email) items.push(`<p><strong>Email:</strong> <a href="mailto:${escapeAttr(contact.email)}">${escapeText(contact.email)}</a></p>`);
  if (contact.address) items.push(`<p><strong>Endereço:</strong> ${escapeText(contact.address)}</p>`);
  if (items.length === 0) items.push(`<p>Entre em contato pelo formulário ou redes sociais.</p>`);
  return items.map(i => `        ${i}`).join("\n");
}

function escapeAttr(s) { return String(s).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])); }
function escapeText(s) { return String(s).replace(/[<>&]/g, c => ({"<":"&lt;",">":"&gt;","&":"&amp;"}[c])); }

module.exports = { buildCopy, HERO_HEADLINES, HERO_SUBHEADS, HERO_CTAS };
